In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv('data.csv')

In [2]:
data['class'] = data['class'].map({'P':1, 'H': 0})

In [3]:
a = data.columns
len(a)

452

In [4]:
data.head(-5)

,ID,air_time1,disp_index1,gmrt_in_air1,gmrt_on_paper1,max_x_extension1,max_y_extension1,mean_acc_in_air1,mean_acc_on_paper1,mean_gmrt1,...,mean_jerk_in_air25,mean_jerk_on_paper25,mean_speed_in_air25,mean_speed_on_paper25,num_of_pendown25,paper_time25,pressure_mean25,pressure_var25,total_time25,class
0,id_1,5160,0.000013,120.804174,86.853334,957,6601,0.361800,0.217459,103.828754,...,0.141434,0.024471,5.596487,3.184589,71,40120,1749.278166,296102.76760,144605,1
1,id_2,51980,0.000016,115.318238,83.448681,1694,6998,0.272513,0.144880,99.383459,...,0.049663,0.018368,1.665973,0.950249,129,126700,1504.768272,278744.28500,298640,1
2,id_3,2600,0.000010,229.933997,172.761858,2333,5802,0.387020,0.181342,201.347928,...,0.178194,0.017174,4.000781,2.392521,74,45480,1431.443492,144411.70550,79025,1
3,id_4,2130,0.000010,369.403342,183.193104,1756,8159,0.556879,0.164502,276.298223,...,0.113905,0.019860,4.206746,1.613522,123,67945,1465.843329,230184.71540,181220,1
4,id_5,2310,0.000007,257.997131,111.275889,987,4732,0.266077,0.145104,184.636510,...,0.121782,0.020872,3.319036,1.680629,92,37285,1841.702561,158290.02550,72575,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164,id_165,2410,0.000014,325.502346,185.715475,2221,10056,0.418182,0.139988,255.608911,...,0.069589,0.023235,2.612125,2.112848,115,44255,1110.545136,184100.17520,125525,0
165,id_166,2960,0.000016,335.098534,205.144777,1498,11349,0.257536,0.135660,270.121655,...,0.151684,0.019807,4.333400,3.551515,78,39235,1613.190774,135471.60180,62585,0
166,id_167,8735,0.000012,321.354345,158.889068,1379,9171,1.692302,0.176674,240.121706,...,0.197694,0.019259,5.114071,2.788386,80,32190,1903.081702,93727.84079,341405,0
167,id_168,2039,0.000013,323.101817,206.158451,2703,10615,0.232597,0.161851,264.630134,...,0.161790,0.025171,6.093337,3.149393,108,35380,1706.291549,202363.75290,66470,0
168,id_169,5645,0.000009,183.410171,240.965953,2215,8304,0.685004,0.179760,212.188062,...,0.165098,0.018266,4.737876,2.827065,88,35825,1732.632798,182613.98110,69270,0

In [5]:
df =data.drop(columns=['ID'], axis=1)

In [6]:
col_means = df.mean(axis=0)
col_stds = df.std(axis=0)

In [7]:
col_means

air_time1             5664.166667
disp_index1              0.000010
gmrt_in_air1           297.666685
gmrt_on_paper1         200.504413
max_x_extension1      1977.965517
                        ...
paper_time25         43109.712644
pressure_mean25       1629.585962
pressure_var25      163061.767360
total_time25        164203.327586
class                    0.511494
Length: 451, dtype: float64

In [8]:
n_new_data = 400

In [9]:
new_data = pd.DataFrame(columns=df.columns, index=range(n_new_data))

In [10]:
new_data

,air_time1,disp_index1,gmrt_in_air1,gmrt_on_paper1,max_x_extension1,max_y_extension1,mean_acc_in_air1,mean_acc_on_paper1,mean_gmrt1,mean_jerk_in_air1,...,mean_jerk_in_air25,mean_jerk_on_paper25,mean_speed_in_air25,mean_speed_on_paper25,num_of_pendown25,paper_time25,pressure_mean25,pressure_var25,total_time25,class
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
397,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
398,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
for i in range(n_new_data):
    noise = np.random.normal(0, col_stds, size=df.shape[1])
    new_row = col_means + noise
    new_data.iloc[i] = new_row

In [12]:
new_data.drop(columns=['class'], axis=1)

,air_time1,disp_index1,gmrt_in_air1,gmrt_on_paper1,max_x_extension1,max_y_extension1,mean_acc_in_air1,mean_acc_on_paper1,mean_gmrt1,mean_jerk_in_air1,...,mean_gmrt25,mean_jerk_in_air25,mean_jerk_on_paper25,mean_speed_in_air25,mean_speed_on_paper25,num_of_pendown25,paper_time25,pressure_mean25,pressure_var25,total_time25
0,25861.924785,0.000012,350.022884,89.669548,4850.632015,5037.08723,-0.543859,0.153858,220.166853,-0.041739,...,250.820989,0.123522,0.01668,5.138722,2.947498,66.200169,50117.355397,1215.445299,118881.726198,626247.442181
1,16444.612103,0.00001,163.553319,415.774703,2233.439996,8782.926364,0.954797,0.177974,284.191399,0.076744,...,126.796767,0.085794,0.017218,3.298136,2.417049,50.538222,-16532.600535,1879.575136,117595.461879,545634.458859
2,-2264.324668,0.000011,508.173908,-17.967482,3603.407477,7678.875555,0.368709,0.313984,213.776009,-0.036951,...,117.456263,0.175543,0.021807,4.123738,2.501712,37.848837,68119.604173,1734.836202,102506.334048,1046406.473831
3,-7886.358927,0.00001,484.404227,124.335702,859.135734,10018.159549,-0.36458,0.005432,282.767766,0.033148,...,158.340931,0.116132,0.021808,3.100174,2.843789,77.277934,77699.136118,1987.861431,113442.083714,335202.947006
4,10675.688565,0.000005,605.532298,208.30626,1624.299373,8423.324471,0.216446,0.205763,377.037832,0.059152,...,290.863442,0.158168,0.018525,4.244096,1.211252,96.722435,47724.85366,2561.707177,139858.478549,-27466.607042
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,16789.506755,0.000012,374.707859,237.709974,1901.853275,9504.730302,0.711944,0.236973,374.10945,0.037447,...,181.12908,0.155654,0.01914,4.010181,2.966102,75.242143,65522.617592,1510.774042,200766.438634,733548.597217
396,5974.274549,0.000012,-263.77015,318.371425,726.231393,6583.500678,-0.366499,0.171506,429.22954,0.112442,...,204.927586,0.14944,0.020987,4.602647,3.282483,89.269708,69668.256886,1349.839673,219960.085808,-439740.240285
397,12305.657629,0.000008,229.262256,60.952735,1099.348429,7339.236626,0.274691,0.287386,336.28462,0.201294,...,237.929574,0.170808,0.021154,4.5079,3.482041,92.239557,36962.846527,1727.90859,183279.11217,-729204.762974
398,16824.928143,0.000007,167.692861,191.177153,5469.019405,12347.444445,0.016751,0.083117,185.517814,0.16947,...,34.50867,0.127337,0.016507,3.594168,2.774254,35.037221,56991.727917,1952.041372,173337.251062,-5088.499923
399,8496.460775,0.000009,46.439003,226.091319,2551.037666,9921.944723,0.64385,0.173211,341.378792,0.10102,...,260.152261,0.161963,0.016281,2.469842,4.111107,92.42476,45157.250009,1886.67683,139217.819397,619953.188022

In [13]:
augmented_data = pd.concat([df, new_data])

In [14]:
augmented_data.head()

,air_time1,disp_index1,gmrt_in_air1,gmrt_on_paper1,max_x_extension1,max_y_extension1,mean_acc_in_air1,mean_acc_on_paper1,mean_gmrt1,mean_jerk_in_air1,...,mean_jerk_in_air25,mean_jerk_on_paper25,mean_speed_in_air25,mean_speed_on_paper25,num_of_pendown25,paper_time25,pressure_mean25,pressure_var25,total_time25,class
0,5160,0.000013,120.804174,86.853334,957,6601,0.3618,0.217459,103.828754,0.051836,...,0.141434,0.024471,5.596487,3.184589,71,40120,1749.278166,296102.7676,144605,1
1,51980,0.000016,115.318238,83.448681,1694,6998,0.272513,0.14488,99.383459,0.039827,...,0.049663,0.018368,1.665973,0.950249,129,126700,1504.768272,278744.285,298640,1
2,2600,0.00001,229.933997,172.761858,2333,5802,0.38702,0.181342,201.347928,0.06422,...,0.178194,0.017174,4.000781,2.392521,74,45480,1431.443492,144411.7055,79025,1
3,2130,0.00001,369.403342,183.193104,1756,8159,0.556879,0.164502,276.298223,0.090408,...,0.113905,0.01986,4.206746,1.613522,123,67945,1465.843329,230184.7154,181220,1
4,2310,0.000007,257.997131,111.275889,987,4732,0.266077,0.145104,184.63651,0.037528,...,0.121782,0.020872,3.319036,1.680629,92,37285,1841.702561,158290.0255,72575,1

In [15]:
original_labels = df['class'].to_numpy()
label_counts = np.unique(original_labels, return_counts=True)
class_probs = label_counts[1] / np.sum(label_counts)

In [16]:
class_probs = np.array([class_probs[i] if i < len(class_probs) else class_probs[-1] for i in range(len(label_counts[0]))])

In [17]:
class_probs /= np.sum(class_probs)

In [18]:
new_labels = np.random.choice(label_counts[0], size = n_new_data, p = class_probs)

In [19]:
new_labels

array([1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0])

In [20]:
original_labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
y = np.concatenate([original_labels, new_labels])

In [22]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0])

In [23]:
len(y)

574

In [25]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(augmented_data)

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.15, random_state=42)

In [27]:
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.regularizers import L1, L2

In [40]:
model = Sequential()
model.add(Dense(1024, activation='relu', input_dim = X_train.shape[1]))
model.add(Dense(1024, activation='relu', ))
model.add(Dense(1024, activation='relu'))
model.add(Dense(1024, activation='relu'))
model.add(Dense(1024, activation='relu'))
model.add(Dense(1024, activation='relu'))
model.add(Dense(1024, activation='relu'))
model.add(Dense(1024, activation='relu'))
model.add(Dense(1024, activation='relu'))
model.add(Dense(1024, activation='relu'))
model.add(Dense(1024, activation='relu'))
model.add(Dense(1024, activation='relu'))

model.add(Dense(1))

model.compile(optimizer='adam', loss='mse', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=10, validation_data=(X_test, y_test), validation_batch_size=5)

Epoch 1/10
49/49 [==============================] - 1s 6ms/step - loss: 1.4276 - accuracy: 0.5359 - val_loss: 1.5828 - val_accuracy: 0.5057
Epoch 2/10
49/49 [==============================] - 0s 5ms/step - loss: 3.1750 - accuracy: 0.7146 - val_loss: 0.5433 - val_accuracy: 0.5057
Epoch 3/10
49/49 [==============================] - 0s 5ms/step - loss: 0.6092 - accuracy: 0.6550 - val_loss: 0.3737 - val_accuracy: 0.5862
Epoch 4/10
49/49 [==============================] - 0s 5ms/step - loss: 0.1084 - accuracy: 0.9322 - val_loss: 0.3415 - val_accuracy: 0.5747
Epoch 5/10
49/49 [==============================] - 0s 5ms/step - loss: 0.0410 - accuracy: 0.9877 - val_loss: 0.3248 - val_accuracy: 0.5977
Epoch 6/10
49/49 [==============================] - 0s 5ms/step - loss: 0.0100 - accuracy: 1.0000 - val_loss: 0.3282 - val_accuracy: 0.5632
Epoch 7/10
49/49 [==============================] - 0s 6ms/step - loss: 0.0048 - accuracy: 0.9979 - val_loss: 0.3267 - val_accuracy: 0.5862
Epoch 8/10
49/49 [==============================] - 0s 5ms/step - loss: 0.0031 - accuracy: 1.0000 - val_loss: 0.3298 - val_accuracy: 0.5977
Epoch 9/10
49/49 [==============================] - 0s 5ms/step - loss: 0.0019 - accuracy: 1.0000 - val_loss: 0.3260 - val_accuracy: 0.5862
Epoch 10/10
49/49 [==============================] - 0s 5ms/step - loss: 0.0017 - accuracy: 1.0000 - val_loss: 0.3291 - val_accuracy: 0.5862